### ISSUE TITLE
Landing page confirmation

### ISSUE THREAD

**Issue by minaorangina** [ayooo-team/landing-page#36]
@PAOLOPRIAMODAMU here is the link for the landing page.

The app is currently hosted under: [ayooo.herokuapp.com](https://ayooo.herokuapp.com).

Please can you confirm you've seen it and make any comments in this issue :smile:

**Comment by mk4111** [comment]
@PAOLOPRIAMODAMU hope the website is looking similar to what you had hoped :)

Just a quick mention about the subscription form - we used the GoogleForms service instead of MailChimp because it seems that we can't opt out of the 'Please Confirm' email sent to clients, which if we remember correctly, was raised as a bit of a problem as it needed people to check their email and confirm their subscription. 

We found out that it is quite easy to import all the user details collected from GoogleForms, and import them into MailChimp, so we hope that's ok! Please let us know what you think!

**Comment by minaorangina** [comment]
@PAOLOPRIAMODAMU Can you please review the tweaks we have made to the site?  The relevant issues are listed below:
#38 #39 #40 #41
